spring:
  kafka:
    # Streams ????? bootstrap-servers ??? ?? ???? ?? spring.kafka.bootstrap-servers? ????.
    # https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.2.1/reference/html/spring-cloud-stream-binder-kafka.html#_setting_up_bootstrap_server_configuration
    bootstrap-servers: localhost:9092
  # Multiple Kafka Streams processors? ??? ??? Application?? ?? ??? ???? ??? ??? ?????.
  # https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.2.1/reference/html/spring-cloud-stream-binder-kafka.html#_multiple_kafka_streams_processors_within_a_single_application
  cloud:
    stream:
      function:
        definition: kafkaStreamsYellingApp
      bindings:
        kafkaStreamsYellingApp-in-0:
          destination: src-topic
      kafka:
        streams:
          binder:
            functions:
              kafkaStreamsYellingApp:
                applicationId: kafkaStreamsYellingApp
          bindings:
            kafkaStreamsYellingApp-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
