spring:
  kafka:
    # Streams ????? bootstrap-servers ??? ?? ???? ?? spring.kafka.bootstrap-servers? ????.
    # https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.2.1/reference/html/spring-cloud-stream-binder-kafka.html#_setting_up_bootstrap_server_configuration
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      batch-size: 1000000
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 100

  # Multiple Kafka Streams processors? ??? ??? Application?? ?? ??? ???? ??? ??? ?????.
  # https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.2.1/reference/html/spring-cloud-stream-binder-kafka.html#_multiple_kafka_streams_processors_within_a_single_application
  cloud:
    stream:
      function:
        definition: kafkaStreamsYellingApp;zMartStreamApplication
      bindings:
        # KafkaStreams Bindings inbound consumer에 useNativeDecoding을 사용할떄 주의해야한다. useNativeDecoding: false로 선언시 설정한 Serde와 관계 없이 ByteArraySerde를 사용하게 된다.
        # KeyValueSerdeResolver.getInboundValueSerde에서 확인 가능
        # KStreamBoundElementFactory.createInput 에서 Default를 true로 설정해준다.
        kafkaStreamsYellingApp-in-0:
          destination: src-topic
          consumer:
            concurrency: 1
        zMartStreamApplication-in-0:
          destination: transaction
          consumer:
            concurrency: 1
      kafka:
        streams:
          binder:
            functions:
              kafkaStreamsYellingApp:
                applicationId: kafkaStreamsYellingApp
              zMartStreamApplication:
                applicationId: zMartStreamApplication
            configuration:
              replication.factor: 3
              default:
                key.serde: org.springframework.kafka.support.serializer.JsonSerde
                # default.value.serde는 useNativeDecoding = true && Bindings에 valueSerde에 설정이 되어있지 않을 경우에만 동작한다
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
          bindings:
            kafkaStreamsYellingApp-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
            zMartStreamApplication-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.kafkastreamsinaction.serde.PurchaseSerde

